#!/bin/sh

for compiler in "--enable-gcc" "--enable-icc"; do
for options in "--code-caching false --loop-fusion false --array-contraction false --liveness-analysis false" \
               "--code-caching true --loop-fusion false --array-contraction false --liveness-analysis false" \
               "--code-caching true --loop-fusion true --array-contraction false --liveness-analysis false" \
               "--code-caching true --loop-fusion true --array-contraction true --liveness-analysis false" \
               "--code-caching true --loop-fusion true --array-contraction true --liveness-analysis true"; do
for solver in identity_bicg identity_bicgstab identity_cgs identity_qmr identity_tfqmr; do
for matrix in "../test-matrices/sherman5.rua" "../test-matrices/bcsstk14.rsa" ; do
  echo -n -e "Solver: $solver\t"
  ./$solver $compiler $options --iterations 256 --single-line $matrix | grep "^Library:";
done;
done;
done;
done;
