#!/bin/sh

./cached_stats | tee -a cached_stats.txt &&
./fused_stats | tee -a fused_stats.txt &&
./contraction_stats | tee -a contraction_stats.txt &&
./liveness_stats | tee -a liveness_stats.txt&&
./mtl_stats | tee -a mtl_stats.txt
