#!/bin/sh

ITL_TEST_PATH="../itl-tests"
MATRIX_PATH="../test-matrices"

for compiler in "--enable-icc"; do
for options in "--code-caching true --loop-fusion false --array-contraction false --liveness-analysis false" \
               "--code-caching true --loop-fusion true --array-contraction false --liveness-analysis false" \
	       "--code-caching true --loop-fusion true --array-contraction true --liveness-analysis false" \
	       "--code-caching true --loop-fusion true --array-contraction true --liveness-analysis true"; do
for solver in identity_bicg identity_bicgstab identity_cgs identity_qmr identity_tfqmr; do
for matrix in bcsstk14.rsa sherman5.rua bcsstk15.rsa sherman3.rua; do
  echo -n -e "Solver: $solver\t"
  $ITL_TEST_PATH/$solver $compiler $options --iterations 256 --single-line $MATRIX_PATH/$matrix | grep "^Library:";
done;
done;
done;
done;
