#!/bin/bash

. ./solver_invoker

SOLVER_PATH="../atlas-itl-tests"
MATRIX_PATH="../benchmark-matrices"
SOLVERS="identity_bicg identity_bicgstab identity_cgs identity_qmr identity_tfqmr"
MATRICES=$(find -H ${MATRIX_PATH} -name "*.rua")
unset SOLVER_OPTIONS

invoke_solvers
