#!/bin/sh

ATLAS_ITL_TEST_PATH="../atlas-itl-tests"
MATRIX_PATH="../benchmark-matrices"

for solver in identity_bicg identity_bicgstab identity_cgs identity_qmr identity_tfqmr; do
for matrix in $(find ${MATRIX_PATH} -name "*.rua"); do
  echo -n -e "Solver: $solver\t"
  $ATLAS_ITL_TEST_PATH/$solver --iterations 256 --single-line $matrix | grep "^Library:";
done;
done;
