#! /bin/bash

getValue()
{
  pcregrep o ":$1=.*?:" | sed -r "s/^:.*=(.*):$/\1/"
}

iterationspec="iterations=256:"
for solver in identity_bicg identity_bicgstab identity_cgs identity_qmr identity_tfqmr; do
echo "#Solver: $solver"
for matsize in $(cat "$1" | getValue mat_n | sort -n | uniq); do

#Size
echo -n "$matsize "
#Desola Timing Columns
for linespec in ":solver=$solver:lib=desola:.*:mat_n=$matsize:.*:code_cache=on:fusion=off:contraction=off:liveness=off:" \
                ":solver=$solver:lib=desola:.*:mat_n=$matsize:.*:code_cache=on:fusion=on:contraction=off:liveness=off:" \
                ":solver=$solver:lib=desola:.*:mat_n=$matsize:.*:code_cache=on:fusion=on:contraction=on:liveness=off:" \
                ":solver=$solver:lib=desola:.*:mat_n=$matsize:.*:code_cache=on:fusion=on:contraction=on:liveness=on:"; do
# Average Evaluation Time
grep -E "$linespec" "$1" | grep -E ":$iterationspec" | getValue total_time | average | tr "\n" " "
# Average Compile Time
grep -E "$linespec" "$1" | grep -E ":$iterationspec" | getValue compile_time | average | tr "\n" " "
done;

#MTL Timing Column
grep -E ":solver=$solver:lib=mtl:.*:mat_n=$matsize:$iterationspec" "$1" | getValue total_time | average | tr "\n" " "

#ATLAS Timing Column
grep -E ":solver=$solver:lib=atlas:.*:mat_n=$matsize:$iterationspec" "$1" | getValue total_time | average | tr "\n" " "

#IMKL Timing Column
grep -E ":solver=$solver:lib=imkl:.*:mat_n=$matsize:$iterationspec" "$1" | getValue total_time | average | tr "\n" " "

#FLOP Column
grep -E ":solver=$solver:lib=desola:.*:mat_n=$matsize:code_cache=on:fusion=on:contraction=on:liveness=off:$iterationspec" "$1" | getValue flop | head -n1 | tr "\n" " "

# End of column newline
echo 
done;

#End of Solver
echo
echo

done;
