#! /bin/bash

iterationspec="Iterations: 256"
for solver in identity_bicg identity_bicgstab identity_cgs identity_qmr identity_tfqmr; do

for matrix in $(grep "Matrix:" "$1" | sed -r "s/.*Matrix: ([[:graph:]]*).*/\1/" | sort | uniq); do
echo -n "${solver}  "
echo -n "${matrix}  " | sed -r "s/(.*)\.[[:graph:]]*/\1/"
grep -E "Matrix: ${matrix}[[:space:]]+" "$1" | grep -o -E "NNZ: ([0-9]*)" | sed -r "s/NNZ: //" | head -n1 | tr "\t\n" "  "
grep -E "Matrix: ${matrix}[[:space:]]+" "$1" | grep -o -E "Matrix Size: ([0-9]*)" | sed "s/Matrix Size: //" | head -n1 | tr "\t\n" "  "

#Desolin Timing Columns
for linespec in "^Solver: ${solver}[[:space:]]+Library: desolin.*Matrix: ${matrix}[[:space:]]+.*Code_cache: On.*Fusion: Off.*Contraction: Off.*Liveness: Off.*$" \
                "^Solver: ${solver}[[:space:]]+Library: desolin.*Matrix: ${matrix}[[:space:]]+.*Code_cache: On.*Fusion: On.*Contraction: Off.*Liveness: Off.*$" \
		"^Solver: ${solver}[[:space:]]+Library: desolin.*Matrix: ${matrix}[[:space:]]+.*Code_cache: On.*Fusion: On.*Contraction: On.*Liveness: Off.*$" \
		"^Solver: ${solver}[[:space:]]+Library: desolin.*Matrix: ${matrix}[[:space:]]+.*Code_cache: On.*Fusion: On.*Contraction: On.*Liveness: On.*$"; do
# Average Evaluation Time
grep -E "${linespec}" "$1" | grep "${iterationspec}" | clm 29 | average | tr "\n" " "
# Average Compile Time
grep -E "${linespec}" "$1" | grep "${iterationspec}" | clm 25 | average | tr "\n" " "
done;

#MTL Timing Column
grep -E "^Solver: ${solver}[[:space:]]+Library: MTL.*Matrix: ${matrix}[[:space:]]+.*$" "$1" | grep "${iterationspec}" | clm 15 | average | tr "\n" " "

#IMKL Timing Column
grep -E "^Solver: ${solver}[[:space:]]+Library: IMKL.*Matrix: ${matrix}[[:space:]]+.*$" "$1" | grep "${iterationspec}" | clm 15 | average | tr "\n" " "

#FLOPs Column
grep -E "^Solver: ${solver}[[:space:]]+Library: desolin.*Matrix: ${matrix}[[:space:]]+.*Code_cache: On.*Fusion: On.*Contraction: On.*Liveness: Off.*$" "$1" | grep "${iterationspec}" | clm 31 | head -n1 | tr "\n" " "

# End of column newline
echo 
# Another 2 newlines to separate datasets
echo; echo

done;

done;
