#! /bin/bash

iterationspec="Iterations:[^0-9]256"
for solver in identity_bicg identity_bicgstab identity_cgs identity_qmr identity_tfqmr; do

for nnz in $(grep -Eo "NNZ: [0-9]*$" "$1" | sed "s/NNZ: //" | sort -n | uniq); do

#Size
echo -n "${solver}  "
grep -E "NNZ: ${nnz}$" "$1" | grep -o "Matrix: [A-Za-z0-9_]*\.[A-Za-z]*[^A-Za-z]" | sed -r "s/Matrix: ([A-Za-z0-9_]*)\..*/\1/" | head -n1 | tr "\t\n" "  "
echo -n "${nnz} "
grep -E "NNZ: ${nnz}$" "$1" | grep -o "Matrix Size: [0-9]*[^0-9]" | sed "s/Matrix Size: //" | head -n1 | tr "\t\n" "  "

#Desolin Timing Columns
for linespec in "Solver: $solver[^a-zA-Z]*Library: desolin.*Code_cache: On.*Fusion: Off.*Contraction: Off.*Liveness: Off.*NNZ: ${nnz}$" \
                "Solver: $solver[^a-zA-Z]*Library: desolin.*Code_cache: On.*Fusion: On.*Contraction: Off.*Liveness: Off.*NNZ: ${nnz}$" \
		"Solver: $solver[^a-zA-Z]*Library: desolin.*Code_cache: On.*Fusion: On.*Contraction: On.*Liveness: Off.*NNZ: ${nnz}$" \
		"Solver: $solver[^a-zA-Z]*Library: desolin.*Code_cache: On.*Fusion: On.*Contraction: On.*Liveness: On.*NNZ: ${nnz}$"; do
# Average Evaluation Time
grep -E "$linespec" "$1" | grep -E "$iterationspec" | clm 29 | average | tr "\n" " "
# Average Compile Time
grep -E "$linespec" "$1" | grep -E "$iterationspec" | clm 25 | average | tr "\n" " "
done;

#MTL Timing Column
grep -E "Solver: $solver[^a-zA-Z]*Library: MTL.*NNZ: ${nnz}$" "$1" | grep -E "$iterationspec" | clm 15 | average | tr "\n" " "

#IMKL Timing Column
grep -E "Solver: $solver[^a-zA-Z]*Library: IMKL.*NNZ: ${nnz}$" "$1" | grep -E "$iterationspec" | clm 15 | average | tr "\n" " "

#FLOPs Column
grep -E "Solver: $solver[^a-zA-Z]*Library: desolin.*Code_cache: On.*Fusion: On.*Contraction: On.*Liveness: Off.*NNZ: ${nnz}$" "$1" | grep -E "$iterationspec" | clm 31 | head -n1 | tr "\n" " "

# End of column newline
echo 
# Another 2 newlines to separate datasets
echo; echo

done;

done;
