#!/bin/sh

ITL_TEST_PATH="../itl-tests"
MATRIX_PATH="../benchmark-matrices"

for compiler in "--enable-icc"; do
for solver in identity_bicg identity_bicgstab identity_cgs identity_qmr identity_tfqmr; do
for matrix in $(find ${MATRIX_PATH} -name "*.rua"); do
  echo -n -e "Solver: $solver\t"
  $ITL_TEST_PATH/$solver $compiler --code-caching true --loop-fusion true --array-contraction true --liveness-analysis true --iterations 256 --single-line $MATRIX_PATH/$matrix | grep "^Library:";
done;
done;
done;
