#!/bin/bash

. ./solver_invoker

SOLVER_PATH="../itl-tests"
MATRIX_PATH="../test-matrices"
SOLVERS="identity_bicg identity_bicgstab identity_cgs identity_qmr identity_tfqmr"
MATRICES="bcsstk14.rsa"
SOLVER_OPTIONS="--enable-icc --code-caching=false --loop-fusion=false --array-contraction=false --liveness-analysis=false"

invoke_solvers
